import { Socio } from './ISocio';

export const SOCIOS: Socio[] = [
    {
        id: 1,
        nombre: 'Jorge',
        apellido: 'Sequiera',
        cedula: '001-123456-1234A',
        sexo: 'Hombre',
        correo: 'jse@mail.com',
        fechaIngreso: '2020-04-20',
        pagoCategoria: 'B',
        pagoFrecuencia: 'Mensual',
        cargo: 'SEO',
        empresa: 'Waishar',
        telefonoCelular: '8811223344',
        telefonoEmpresa: '77992244',
        direccion: 'Del palo de mango, 300 varas al sur',
        comentario: 'SEO',
        contactoPago: 'Correo Personal',
    },
    {
        id: 2,
        nombre: 'Maria',
        apellido: 'Alvarez',
        cedula: '001-123456-1234A',
        sexo: 'Mujer',
        correo: 'maz@mail.com',
        fechaIngreso: '2022-05-05',
        pagoCategoria: 'A',
        pagoFrecuencia: 'Bimensual',
        cargo: 'Manager',
        empresa: 'Petronic',
        telefonoCelular: '8811223344',
        telefonoEmpresa: '77992244',
        direccion: 'Casa esquinera N. 420',
        comentario: 'Gerente DMS',
        contactoPago: 'Correo Personal',
    },{
        id: 3,
        nombre: 'Clemente',
        apellido: 'Guido',
        cedula: '001-123456-1234A',
        sexo: 'Hombre',
        correo: 'cgd@mail.com',
        fechaIngreso: '2022-03-01',
        pagoCategoria: 'A',
        pagoFrecuencia: 'Bimensual',
        cargo: 'DMS',
        empresa: 'Raspados Loli',
        telefonoCelular: '8811223344',
        telefonoEmpresa: '77992244',
        direccion: 'Bello Horizonte',    
        comentario: 'Rapado',
        contactoPago: 'Correo Personal',
    },
    {
        id: 4,
        nombre: 'Erika',
        apellido: 'Singer',
        cedula: '001-123456-1234A',
        sexo: 'Mujer',
        correo: 'esr@mail.com',
        fechaIngreso: '2022-03-01',
        pagoCategoria: 'B',
        pagoFrecuencia: 'Anual',
        cargo: 'Vice CEO',
        empresa: 'Canal 4',
        telefonoCelular: '8811223344',
        telefonoEmpresa: '77992244',
        direccion: 'Rubenia',
        contactoPago: 'Correo Personal',
        comentario: 'Algun dia',
    },
];